name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For npm provenance
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Validate
        run: pnpm run validate

      - name: Test
        run: pnpm run test

      - name: Publish iris-ecs
        run: pnpm publish -F iris-ecs --provenance --no-git-checks

      - name: Publish iris-react
        run: pnpm publish -F iris-react --provenance --no-git-checks
